(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g3=function(a){a.ea("cardstatechange",a.ph()&&a.fk()?1:0)},h3=function(a,b){var c=g.Ka(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},gMa=function(a){var b=g.Kl(a);
a=g.Ql(a);return new g.rl(b.x,b.y,a.width,a.height)},hMa=function(a){return Math.pow(a,3)},iMa=function(a){return 3*a*a-2*a*a*a},k3=function(a){a=g.Na(a);
delete i3[a];g.Rb(i3)&&j3&&j3.stop()},kMa=function(){j3||(j3=new g.K(function(){jMa()},20));
var a=j3;a.isActive()||a.start()},jMa=function(){var a=g.Qa();
g.Db(i3,function(b){lMa(b,a)});
g.Rb(i3)||kMa()},l3=function(a,b,c,d){g.Rq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.u=null},lMa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.u);a.u=b;mMa(a,a.progress);1==a.progress?(a.Oa=0,k3(a),a.onFinish(),a.Dv()):a.xc()&&a.UA()},mMa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},nMa=function(a,b){g.lf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.Oa},m3=function(a,b,c,d,e){l3.call(this,b,c,d,e);
this.element=a},n3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
m3.call(this,a,b,c,d,e)},o3=function(a){g.F.call(this);
this.l=a||window;this.i=[]},p3=function(a){return a.baseUrl||null},q3=function(a,b){return g.So(g.Re(a,b,void 0),function(c){return!!c})},oMa=function(a,b,c){function d(wa){var Ba,ac,jd,Pb=wa.hovercardButton;
if(!Pb)return null;Pb=Pb.subscribeButtonRenderer;if(!Pb)return null;var ec=f(Pb.unsubscribedButtonText),nc=f(Pb.subscribedButtonText);if(Pb.subscribed){var fg=f(Pb.subscriberCountWithUnsubscribeText);var Tg=f(Pb.subscriberCountText)}else fg=f(Pb.subscriberCountText),Tg=f(Pb.subscriberCountWithSubscribeText);var oc=null;return wa.signinEndpoint&&(oc=h3(wa,"signinEndpoint","webNavigationEndpointData","url"),oc||(oc=null===(jd=null===(ac=null===(Ba=Pb.signInEndpoint)||void 0===Ba?void 0:Ba.commandMetadata)||
void 0===ac?void 0:ac.webCommandMetadata)||void 0===jd?void 0:jd.url),!oc)?null:ec&&(nc||oc)?{subscribed:Pb.subscribed,subscribeText:ec,subscribeCount:fg,unsubscribeText:nc,unsubscribeCount:Tg,enabled:Pb.enabled,signinUrl:oc,classic:wa.useClassicSubscribeButton}:null}
function e(wa){if(wa){var Ba=[],ac=wa.videoId;ac&&Ba.push("v="+ac);(ac=wa.playlistId)&&Ba.push("list="+ac);(wa=wa.startTimeSeconds)&&Ba.push("t="+wa);return"/watch?"+Ba.join("&")}}
function f(wa){if(!wa)return null;var Ba=wa.simpleText;return Ba?Ba:wa.runs?g.Re(wa.runs,function(ac){return ac.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,z=null,G=null,H=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=h3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((G=h3(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=h3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=h3(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:null,Y="";if(b.metadata){var Q=f(b.metadata);Q&&(Y=Q)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Y,callToAction:f(b.callToAction),jI:b.image,
iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,gR:n,Vd:L?{itct:L}:null,RV:p,Et:a?a:null,jR:b.isPlaceholder,impressionUrls:q3(b.impressionUrls||[],p3),ZQ:q3(b.hovercardShowUrls||[],p3),clickUrls:q3(l.loggingUrls||[],p3),visualElement:g.Xx(b.trackingParams),productPrice:H,
additionalFeesText:I}},r3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:q3(a.impressionUrls||[],p3),elements:q3(a.elements||[],function(d,e){return oMa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Xx(a.trackingParams));return c},s3=function(a){g.rN.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.V=!0;this.G=0;a=a.T();this.L=g.DF(a)||g.HF(a);this.events=new g.kN(this);g.J(this,this.events);this.events.N(this.player,g.dA("creatorendscreen"),this.Ad);this.events.N(this.player,g.eA("creatorendscreen"),this.lf);this.events.N(this.player,"resize",this.tb);this.events.N(window,"focus",this.aV);this.load();var b=g.qg("STYLE");(g.bg("HEAD")[0]||document.body).appendChild(b);g.kf(this,function(){g.ug(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},pMa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},t3=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},qMa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=r3(f,pMa(a))));u3(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.ip;d&&(c.postParams={ad_tracking:d});if(b=g.Vna(b))if(b=g.Mc(b),b=g.Ic(b))a.u=g.it(b,c)},u3=function(a,b,c){c=void 0===c?!0:c;
a.player.Te("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&rMa(a);c=[];d=new g.aA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.V({D:"div",K:"ytp-ce-shadow"}),g.hN(a.player,a.l.element,4),a.B=new g.UL(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=sMa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.hN(a.player,f.element,4);var h=new g.aA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);tMa(a,f,e)}else g.oy(new g.Xv("buildEndscreenElement null",
e))}a.player.Gd(c);a.tb()}},rMa=function(a){var b=g.ay(),c=g.cy();
c&&b&&a.endscreen.visualElement&&g.fz(void 0,c,b,[a.endscreen.visualElement])},sMa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.X("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Fa:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Et||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:v3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:w3(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Fa:["ytp-ce-video-title"].concat(g.v(c)),U:{dir:g.Xq(b.title||
"")},ra:b.title},{D:"div",K:"ytp-ce-video-duration",ra:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.X("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Fa:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Et||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:v3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:w3(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Fa:["ytp-ce-playlist-title"].concat(g.v(c)),U:{dir:g.Xq(b.title||"")},ra:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ra:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Fa:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Et||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Fa:["ytp-ce-channel-title","ytp-ce-link"],U:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Xq(b.title||"")},ra:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ra:b.subscribersText}:"",b.metadata?{D:"div",Fa:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ra:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:v3(b)}]};c=new g.V(c);var d=g.cg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Vd.itct}else e="endscreen",f=null;e=new g.wO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Fa:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Et||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.Xq(b.title||"")},ra:b.title},{D:"div",K:"ytp-ce-website-metadata",ra:b.metadata},{D:"a",Fa:["ytp-ce-website-goto","ytp-ce-link"],U:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:v3(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:uMa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",ra:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ra:b.additionalFeesText})),a={D:"div",Fa:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Et||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.Xq(b.title||"")},ra:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ra:b.metadata},{D:"a",Fa:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:v3(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ra:b.callToAction||void 0}]}]},c=new g.V(a)}b.jR&&g.M(c.element,"ytp-ce-placeholder");return c},v3=function(a){if(a.jI)var b=a.jI.thumbnails;
return uMa(b?b[b.length-1].url:null)},uMa=function(a){return a?{style:"background-image: url("+a+")"}:{}},tMa=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.M(b.element,"ytp-ce-force-expand"),x3(a,c.id,!0)):(g.Oq(b.element,"ytp-ce-force-expand"),g.Oq(b.element,"ytp-ce-element-hover"),x3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){y3(a,b,c)});
b.Qa("mouseleave",function(){z3(a,b,c)});
a.player.T().i||b.Qa("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){vMa(a,c,m)});
b.Qa("keypress",function(m){vMa(a,c,m)});
b.Qa("focus",function(){y3(a,b,c)});
b.Qa("blur",function(){z3(a,b,c)});
b.Qa("touchstart",function(){y3(a,b,c)});
var l=g.eg("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Oq(b.element,"ytp-ce-element-hover");g.Oq(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.eg("ytp-sb-subscribe",b.element));d(g.eg("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},vMa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Mq(d,"ytp-ce-element");){g.Mq(d,"subscribe-label")&&A3(a,b);
if(g.Mq(d,"ytp-ce-channel-subscribe"))return;d=g.vg(d)}if(!d||g.Mq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])z3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.RV)A3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Mc(w3(a,b.targetUrl)),c=g.Ic(c),g.VJ(c,void 0,b.Vd);else{var e=a.player.getVideoData().C,f=function(){var h=w3(a,b.targetUrl),l=b.Vd,m=g.ts(h);e&&m&&(m.v||m.list)?a.player.Jj(m.v,l,m.list,!1):g.UJ(h,l)};
A3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},w3=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.hG(a)+b}else return"";return b},y3=function(a,b,c){g.Mq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.K(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),B3(a,c.ZQ),x3(a,c.id,!0))},z3=function(a,b,c){g.Oq(b.element,"ytp-ce-element-hover");
g.Oq(b.element,"ytp-ce-force-expand");x3(a,c.id,!1)},x3=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},B3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||t3(a))c&&c();else{b=wMa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ju(b[a],d)}},A3=function(a,b,c){B3(a,b.clickUrls,c);
(a=g.cy())&&b.gR&&g.oz(a,b.visualElement)},wMa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(xMa(b[d],c));return a},xMa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},yMa=function(a){return Array.isArray(a)&&a.length?a[0]:a},C3=function(a){return"string"===typeof a?a:""},D3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},zMa=function(a){this.externalId=a},AMa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},E3=function(a){return a.value?a.value:null},F3=function(a){if(!a)return null;
var b=g.Mc(C3(a.value));b=g.Ic(b);if(!b)return null;var c=D3(a.target,BMa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new AMa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},CMa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},FMa=function(a){if(!a)return null;
var b=D3(a.type,DMa),c=D3(a.trigger,EMa),d=yMa(a.url);d=F3(d?d:null);a=yMa(a.subscribeData);var e=a?a:null;e?(a=C3(e.external_user_id),e=C3(e.subscription_token),a=a&&e?new zMa(a):null):a=null;return b?new CMa(b,c,d,a):null},GMa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},IMa=function(a){return(a=HMa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},HMa=function(a,b){return g.eb(a.action,b,void 0)},JMa=function(a,b){this.context=a;
this.i=b},H3=function(a){return a.customMessage?G3("div","iv-card-message",a.customMessage):""},I3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",U:{style:a},S:c}},J3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(G3("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},G3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Xq(c);return{D:a,U:b,ra:c}},KMa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Zw&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Zw+");");c.dir=g.Xq(a.customMessage);var d=[{D:"span",ra:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Fa:b,U:c,S:d}},K3=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Vd,c.tracking.click,5)}},LMa=function(a,b){this.merchant=a;
this.price=b},MMa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},NMa=function(a,b){return b?b:MMa(a)?"current":"new"},L3=function(a,b){g.F.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.Ka=new Map;this.Ra=new Map;this.context.I.addEventListener(g.dA("annotations_module"),function(d){(d=c.Ka.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.eA("annotations_module"),function(d){(d=c.Ra.get(d))&&d.apply(c)})},M3=function(a,b,c,d,e,f,h){a.context.i.Qa(b,"click",function(l){a.VA(c,d,e,f||[],h||0,l)});
a.context.i.Qa(b,"touchstart",function(){a.bb=!1});
a.context.i.Qa(b,"touchmove",function(){a.bb=!0})},OMa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},N3=function(a,b,c){return{gJ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
fM:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Uz:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Q3=function(a,b,c){L3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ja=this.jb=this.u=this.ke=!1;this.xa=null;this.cards=[];this.eb=this.L=this.Ea=this.C=this.Ia=this.i=null;this.Z=[];this.J=this.re=this.Aa=null;this.G=0;this.ya=new g.K(g.Ha,c.W.ud?4E3:3E3);g.J(this,this.ya);this.Ya=new g.K(g.Ha);g.J(this,this.Ya);this.Y=new JMa(c,function(e,f,h,l,m,n){M3(d,e,f,h,l,m,n)});
this.V=new g.V({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Fa:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.J(this,this.V);this.B=this.V.element;this.Ta=new g.UL(this.V,330);g.J(this,this.Ta);this.fb=g.eg("iv-drawer-header-text",this.B);this.l=g.eg("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.jb&&O3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.jb=d.u)&&P3(d)})},PMa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){O3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){P3(a)});
var c=b.headerText;g.xg(a.fb,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Aa=g.Xx(b.trackingParams);a.J=g.Xx(b.closeTrackingParams);a.re=g.Xx(b.iconTrackingParams)},QMa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"simple",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Vd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.command),vl:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?
g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):null,imageUrl:S3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.kA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Zw:null,title:d.title?g.kA(d.title):"",customMessage:d.callToAction?g.kA(d.callToAction):"",url:d.command.urlEndpoint.url?F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};T3(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"collaborator",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Vd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.endpoint),vl:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.kA(d.customText):null,profileImageUrl:S3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.kA(d.channelName):"",metaInfo:[d.subscriberCountText?g.kA(d.subscriberCountText):""],url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};T3(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"playlist",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Vd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.action),vl:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):
null,xw:S3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.kA(d.customMessage):null,playlistVideoCount:g.kA(d.playlistVideoCount),title:d.playlistTitle?g.kA(d.playlistTitle):"",metaInfo:[d.channelName?g.kA(d.channelName):"",d.videoCountText?g.kA(d.videoCountText):""],url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:OMa(d.action)})};T3(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"video",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Vd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.action),vl:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):null,xw:S3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.kA(d.lengthString):null,customMessage:d.customMessage?g.kA(d.customMessage):null,title:d.videoTitle?g.kA(d.videoTitle):"",metaInfo:[d.channelName?g.kA(d.channelName):"",d.viewCountText?g.kA(d.viewCountText):""],isLiveNow:!!d.badge,url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:OMa(d.action)})};T3(a,b)}a.G++},S3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},R3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},SMa=function(a,b){if(b=RMa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.ug(b.NB),g.nb(a.cards,b),a.bx(),U3(a)},O3=function(a,b,c){if(!a.u){a.Ta.show();
a.Ia=new g.K(function(){g.M(a.context.I.getRootNode(),g.JT.IV_DRAWER_OPEN)},0);
a.Ia.start();a.xa=g.hu(a.l,"mousewheel",function(h){a.ya.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.cy();d&&a.Aa&&a.J&&g.mz(d,[a.Aa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.PJ||(f.PJ=!0,TMa(a.context.logger,f.card.tracking.gJ,b)),d&&g.mz(d,[f.card.vl]);g3(a.I);c&&(a.C=new g.K(function(){a.Ea=a.L;a.eb.focus()},330),a.C.start())}},P3=function(a){a.u&&(a.Ta.hide(),g.iu(a.xa),a.xa=null,g.Oq(a.context.I.getRootNode(),g.JT.IV_DRAWER_OPEN),a.u=!1,g3(a.I),a.C&&a.C.stop(),a.C=new g.K(function(){a.Ea&&(a.Ea.focus(),a.Ea=null)},330),a.C.start())},
VMa=function(a){g.Nq(a.element,[g.JT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.hN(a.I,a.B,5);UMa(a);a.L=g.eg("ytp-cards-button",a.I.getRootNode());a.eb=g.eg("iv-drawer-close-button",a.B);a.ke=!0},UMa=function(a){var b=g.eg("iv-drawer-close-button",a.B);
a.context.i.Qa(b,"click",a.GP,a);a.context.i.Qa(a.l,"touchend",function(){a.ya.start()});
a.context.i.Qa(a.l,"scroll",a.UP,a);a.context.l.subscribe("onHideControls",function(){a.Ja=!0});
a.context.l.subscribe("onShowControls",function(){a.Ja=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Ja=g.Mq(a.I.getRootNode(),"ytp-autohide")});
a.Z.push(g.Qu("iv-button-shown",a.rR,a));a.Z.push(g.Qu("iv-button-hidden",a.qR,a));a.Z.push(g.Qu("iv-teaser-shown",a.fO,a));a.Z.push(g.Qu("iv-teaser-hidden",a.tR,a));a.Z.push(g.Qu("iv-teaser-clicked",a.eO,a))},T3=function(a,b){a.ke||VMa(a);
SMa(a,b.id);var c=WMa(a,b);if(c){var d={card:b,NB:c.element,PJ:!1},e=XMa(a,d);g.tb(a.cards,e,0,d);c.Ba(a.l,e);a.bx();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,U3(a),YMa(a,d),O3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&ZMa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){ZMa(a,d)}),U3(a))}},WMa=function(a,b){switch(b.type){case "simple":a=a.Y;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",ra:b.displayDomain}:void 0;var d=KMa(b);c={D:"div",Fa:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?E3(b.url)||"":""},S:[I3(b.imageUrl,c),{D:"div",K:"iv-card-content",S:[G3("h2",void 0,b.title),d]}]}]};c=new g.V(c);K3(a,g.dg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Y,c={D:"div",Fa:["iv-card","iv-card-channel"],S:[{D:"a",Fa:["iv-click-target"],U:{href:E3(b.url)||"","data-ytid":b.channelId},S:[I3(b.profileImageUrl),
{D:"div",K:"iv-card-content",S:[H3(b),{D:"h2",K:"iv-card-primary-link",ra:b.title},J3(b)]}]}]},c=new g.V(c),K3(a,g.dg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Y,c={D:"div",Fa:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:E3(b.url)||""},S:[I3(b.xw,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",ra:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[H3(b),G3("h2","iv-card-primary-link",b.title),J3(b)]}]}]},c=new g.V(c),
K3(a,g.dg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Y;var e=!g.jb(b.offers);c=["iv-card"];d="";var f=KMa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",ra:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",ra:f.merchant}),f={D:"div",S:e});e=b.url?E3(b.url)||"":"";c={D:"div",Fa:c,U:{tabindex:"0"},S:[{D:"a",Fa:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",ra:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:e},S:[G3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.qg("span");g.xg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.cd(d,"adInfo");K3(a,g.dg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Y,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",ra:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Fa:["yt-badge","yt-badge-live"],ra:"LIVE NOW"}:null,d={D:"div",Fa:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(c=b.url)||void 0===c?void 0:E3(c))||""},S:[I3(b.xw,d),{D:"div",K:"iv-card-content",S:[H3(b),G3("h2","iv-card-primary-link",b.title),J3(b),f]}]}]},c=new g.V(d),
K3(a,g.dg("iv-click-target",c.element),b,b.url),c;default:return null}},XMa=function(a,b){if(0===a.cards.length)return 0;
a=g.fb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},$Ma=function(a){return a.i?"productListing"===a.i.card.type:g.Em(a.cards,function(b){return"productListing"===b.card.type})},U3=function(a){g.N(a.I.getRootNode(),"ytp-cards-shopping-active",$Ma(a))},ZMa=function(a,b){if(!g.Mq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.cy(),d=a.i?a.i.card.re:a.re;
c&&d&&g.nz(c,[d]);a.i=b;U3(a)}if(c="none"!=a.element.style.display)g.S(a.context.I.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.rs(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ya.isActive()||((!a.u||!a.ya.isActive()&&a.Ja)&&YMa(a,b),a.Ya.start(910+b.card.teaserDurationMs))}},
YMa=function(a,b){a.V.xb?(b=new l3([0,
a.l.scrollTop],[0,b.NB.offsetTop],600,iMa),a.context.u.Qa(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Qa(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.kL(a.V,!0),a.l.scrollTop=b.NB.offsetTop,g.kL(a.V,!1))},V3=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},RMa=function(a,b){return g.eb(a.cards,function(c){return c.card.id===b})},W3=function(a,b,c){L3.call(this,a,b);
this.annotation=c;this.isActive=!1},aNa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},X3=function(a,b,c){W3.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},bNa=function(a,b){var c=void 0===c?0:c;
var d=gMa(b).width;g.Il(b,d);c=new n3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,hMa);g.J(a,c);a.context.u.Qa(c,"begin",function(){g.Rl(b,!0)});
c.play()},eNa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Fa:["iv-branding-context-name"],ra:b.channel_name}),d=a.createElement({D:"div",Fa:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.wO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Ba(d));var f=a.createElement({D:"div",Fa:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Fa:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Rl(h,!1);var l=a.createElement({D:"div",Fa:["branding-context-container-outer"]});l.appendChild(h);g.Bl(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.K(function(){cNa(a,h,l)},500);
g.J(a,a.u);a.context.i.Qa(a.element,"mouseover",function(){dNa(a,h,l,f,b.image_height)});
a.context.i.Qa(a.element,"mouseout",function(){a.u.start()})}},dNa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Ql(b);a.i||(b.style.width=g.Hl(f.width,!0),c.style.width=g.Hl(f.width,!0));g.Bl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Bl(d,"right","1px");a.B=!0;g.Rl(b,!0);a.C=new g.K(function(){g.M(this.element,"iv-branding-active")},0,a);
a.C.start()}},cNa=function(a,b,c){g.Oq(a.element,"iv-branding-active");
a.G=new g.K(function(){g.Rl(b,!1);a.i||(c.style.width=g.Hl(0,!0))},250);
a.G.start();a.B=!1},fNa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.W=c;this.videoData=d;this.logger=e;this.I=f;this.l=h},Y3=function(a,b,c){W3.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.V=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Fa:["iv-promo-contents"]});this.C=new g.K(function(){d.i.setAttribute("aria-hidden","true");g.Rl(d.u,!1);g.Rl(d.l,!0)},700,this);
g.J(this,this.C)},gNa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=IMa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Fa:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ra:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ra:b.playlist_length.toString()}),h.appendChild(f));e&&M3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.od(f,E3(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
ra:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",ra:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Fa:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Fa:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",ra:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&M3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.i,
"iv-click-target");e&&M3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",ra:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",ra:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Fa:["yt-badge","iv-promo-badge-live"],ra:"LIVE NOW"})),g.M(a.i,"iv-click-target"),e&&M3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Fa:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.Qa(a.l,"click",function(r){Z3(a,5E3,r)});
c.appendChild(a.l);g.Rl(a.l,!1);a.context.i.Qa(a.element,"mouseover",a.DQ,a);a.context.i.Qa(a.element,"mouseout",a.CQ,a);a.context.i.Qa(a.element,"touchend",function(r){Z3(a,5E3,r)});
a.u=a.createElement({D:"button",Fa:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.Qa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.yQ:a.xQ,a);c.appendChild(a.u);g.Nq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},Z3=function(a,b,c){c.stopPropagation();
hNa(a);iNa(a,b);a.i.focus()},jNa=function(a){a.isCollapsed||a.L||a.B||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},hNa=function(a){a.C.stop();
a.isCollapsed&&(g.Pq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Rl(a.l,!1),g.Rl(a.u,!0))},iNa=function(a,b){a.B||(a.B=g.mh(function(){$3(this);
jNa(this)},b,a))},$3=function(a){a.B&&(g.C.clearTimeout(a.B),a.B=null)},kNa=function(a){this.I=a},TMa=function(a,b,c){b&&(c?a4(a,b.map(function(d){return g.Aq(d,c)})):a4(a,b))},a4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Ju(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},b4=function(a){g.rN.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.J={};this.logger=new kNa(this.player);this.C=new g.kN(this);this.G=this.u=null;this.events=new g.kN(this);this.L=this.i=null;this.Z=[];g.J(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.N(this.player,"resize",function(d){b.ea("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.gO,this);this.subscribe("resize",this.Zy,this);this.player.T().V.subscribe("vast_info_card_add",this.dL,this);g.J(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.V({D:"div",Fa:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.l);g.hN(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Fa:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.hq()&&this.load();var c=this.createElement({D:"style"});(g.bg("HEAD")[0]||document.body).appendChild(c);g.kf(this,function(){g.ug(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},lNa=function(a){a=a.createElement({D:"div",
Fa:["annotation","annotation-type-custom"]});g.Rl(a,!1);return a},mNa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.kL(a.l,b);g.kL(a.B,b)},nNa=function(a,b,c){a.V=!0;
a.G=g.it(b,c)},oNa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(oNa(a,e))}return c},rNa=function(a){var b=a.player.getVideoData();
if(b.Ja){var c=a.player.T().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Fs(h)&&h.responseXML?h.responseXML:null)&&c4(a,h)}};
g.Au()&&(d.onFinish=pNa(a,d.onFinish));d.postParams={ic_only:"1"};qNa(d,c);a.V=!0;g.it(b.Ja,d)}}},qNa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Pt&&(a.postParams.ic_coll=b.Pt);b.gx&&(a.postParams.ic_xml=b.gx);b.Aw&&(a.postParams.ic_track=b.Aw)},sNa=function(a){var b=new g.V({D:"div"});
g.Rl(b.element,!1);var c=new Q3(a.player,b.element,d4(a));g.J(c,b);b.Ba(a.l.element);c.ew();return c},d4=function(a){if(!a.L){var b=new o3(a);
g.J(a,b);var c=new g.wk(a);g.J(a,c);a.L=new fNa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.ud)}return a.L},c4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.cy();if(e){var f=g.ay();f&&g.fz(void 0,e,f,[g.Xx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=oNa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=D3(f.type,tNa),p=D3(f.style,uNa),r=C3(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=FMa;if(null==u)var x=null;else if(g.Ka(u)){l=[];for(var y=g.q(u),z=y.next();!z.done;z=y.next()){var G=f(z.value);
G&&l.push(G)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new GMa(m,n,p,x,t):null}else e=null}catch(Ba){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=lNa(f),L=null;switch(l.type){case "branding":if(f.player.T().Hb)break;f.l.element.appendChild(I);L=new X3(I,d4(f),l);break;case "promotion":g.hN(f.player,I,4),L=new Y3(I,d4(f),l)}L&&L.ew();if(f=L)g.J(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=sNa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var Y=e&&e.data&&e.data.card_type;
f=e.data;if(Y)switch(l=f.tracking||{},l={gJ:l.impression,click:l.click,close:l.close,fM:l.teaser_impression,Uz:l.teaser_click},I=f.tracking_params||{},L=null,Y){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Vd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Vd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):
null,re:I.icon?g.Xx(I.icon):null,xw:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "productListing":f.signin_url&&(L=F3({target:"current",value:f.signin_url}));Y=[];for(var Q=f.offers||[],wa=0;wa<Q.length;wa++)Y.push(new LMa(g.vd(Q[wa].merchant),g.vd(Q[wa].price)));e={id:e.id,timestamp:f.timestamp||
0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Vd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Zw:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:F3({pause_on_navigation:f.pause_on_navigation,
target:f.target||"new",value:f.url}),H9:L,G9:f.signin_title?f.signin_title:void 0,F9:f.signin_message?f.signin_message:void 0,offers:Y};T3(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Vd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?
f.display_domain:null,showLinkIcon:!!f.show_link_icon,Zw:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Vd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?
g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,xw:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},T3(c,e)}}else PMa(a.i,e);c=!0}}c&&(g3(a.player),a.Zy())},vNa=function(a,b){var c=!1;
a.i||(a.i=sNa(a),g.J(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(QMa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.kA(b.headerText):"",g.xg(c.fb,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Aa=b.trackingParams?g.Xx(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Xx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.re=b.icon.infoCardIconRenderer.trackingParams?
g.Xx(b.icon.infoCardIconRenderer.trackingParams):null,g3(a.player),a.Zy())},wNa=function(a,b,c,d,e){if(!a.player.T().Hb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new CMa("openUrl","click",new AMa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.kA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.kA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.kA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.kA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.kA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.kA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new GMa(c,"branding","branding",f,d);l=lNa(a);a.l.element.appendChild(l);f=new X3(l,d4(a),f);f.ew();g.J(f,f);a.J[c]=f}},pNa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.Z.push(g.xu(function(){b.apply(null,g.v(d))}))}},xNa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.aN.prototype.rs=g.ca(17,function(a,b){var c=g.IN(this.sb());c&&c.rs(a,b)});
var i3={},j3=null;g.Ra(l3,g.Rq);g.k=l3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Oa)this.progress=0,this.coords=this.i;else if(this.xc())return!1;k3(this);this.startTime=a=g.Qa();-1==this.Oa&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.u=this.startTime;this.progress||this.Vy();this.Xh("play");-1==this.Oa&&this.Xh("resume");this.Oa=1;var b=g.Na(this);b in i3||(i3[b]=this);kMa();lMa(this,a);return!0};
g.k.stop=function(a){k3(this);this.Oa=0;a&&(this.progress=1);mMa(this,this.progress);this.Xh("stop");this.Dv()};
g.k.pause=function(){this.xc()&&(k3(this),this.Oa=-1,this.Xh("pause"))};
g.k.va=function(){0==this.Oa||this.stop(!1);this.Xh("destroy");l3.Wd.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.UA=function(){this.Xh("animate")};
g.k.Xh=function(a){this.dispatchEvent(new nMa(a,this))};
g.Ra(nMa,g.lf);g.Ra(m3,l3);m3.prototype.l=g.Ha;m3.prototype.UA=function(){this.l();m3.Wd.UA.call(this)};
m3.prototype.Dv=function(){this.l();m3.Wd.Dv.call(this)};
m3.prototype.Vy=function(){this.l();m3.Wd.Vy.call(this)};
g.Ra(n3,m3);n3.prototype.l=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(o3,g.F);o3.prototype.Qa=function(a,b,c,d){c=(0,g.D)(c,d||this.l);a=g.hu(a,b,c);this.i.push(a);return a};
o3.prototype.Cy=function(a,b,c,d){c=(0,g.D)(c,d||this.l);a=g.qu(a,b,c);this.i.push(a);return a};
o3.prototype.jc=function(a){g.iu(a);g.nb(this.i,a)};
o3.prototype.va=function(){g.iu(this.i);this.i.length=0;g.F.prototype.va.call(this)};g.w(s3,g.rN);g.k=s3.prototype;g.k.load=function(){g.rN.prototype.load.call(this);if(!t3(this)){var a=g.Wna(this.player.getVideoData());a?(a=r3(a,pMa(this)),u3(this,a,!1)):qMa(this)}};
g.k.unload=function(){u3(this,null);this.u&&(this.u.abort(),this.u=null);g.rN.prototype.unload.call(this)};
g.k.Ye=function(a,b){return t3(this)?"loadCustomEndscreenRenderer"===a?(a=r3(b,"new"),u3(this,a),!0):null:null};
g.k.getOptions=function(){return t3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.tb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<yNa.length;f++){var h=Math.abs(b.width-yNa[f]);if(-1===e||d>=h)e=f,d=h}d=zNa[e];this.l&&g.Bl(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Pl(e.element,Math.round(h.width*a.width),f);g.Il(e.element,m,n);g.Pq(e.element,ANa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Pq(e.element,zNa);g.M(e.element,d);(e=g.cg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Bl(e,"height",f+"px")}}}}};
g.k.Ad=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())B3(this,this.endscreen.impressionUrls),(a=g.cy())&&this.endscreen.visualElement&&g.gz(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");B3(this,c.impressionUrls);(b=g.cy())&&g.gz(b,c.visualElement,void 0);this.player.T().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.lf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Oq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Oq(b,"ytp-ce-shown");this.player.T().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.aV=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Pq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var yNa=[346,426,470,506,570,640,853,1280,1920],zNa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ANa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var BMa={YZ:"current",E4:"new"};var DMa={CLOSE:"close",W4:"openUrl",hP:"subscribe"},EMa={KX:"click",CLOSE:"close",n0:"hidden",g6:"rollOut",h6:"rollOver",U6:"shown"};var uNa={eX:"anchored",QM:"branding",CHANNEL:"channel",WZ:"cta",r0:"highlightText",r1:"label",PLAYLIST:"playlist",C5:"popup",d7:"speech",hP:"subscribe",u7:"title",VIDEO:"video",C8:"website"},tNa={QM:"branding",xX:"card",k_:"drawer",q0:"highlight",W2:"marker",M5:"promotion",TEXT:"text",I8:"widget"};g.w(L3,g.F);g.k=L3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.aA(a,b,{id:c});a.namespace="annotations_module";d&&this.Ka.set(a,d);e&&this.Ra.set(a,e);this.context.I.Gd([a])};
g.k.ew=function(){this.context.l.subscribe("resize",this.bx,this)};
g.k.VA=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ug(this.element)};
g.k.bx=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=E3(a);if(f){var h=NMa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.C||!1,n=g.ts(f||"");m&&n&&(n.v||n.list)?e.context.I.Jj(n.v,b,n.list,!1):g.VJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);a4(this.context.logger,c,l,d);MMa(f)||(c=g.cy(),d=b.itct,c&&d&&g.oz(c,g.Xx(d)))}};
g.k.va=function(){this.Ka.clear();this.Ra.clear();g.F.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.w(Q3,L3);g.k=Q3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Ql(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.bx=function(){var a=this.isAvailable();g.Rl(this.element,a);g.N(this.context.I.getRootNode(),g.JT.IV_DRAWER_ENABLED,a);g3(this.I)};
g.k.destroy=function(){this.I.rs(!1);try{this.I.getRootNode().removeChild(this.B)}catch(a){}g.Ru(this.Z);g.iu(this.xa);this.Ia&&this.Ia.dispose();this.C&&this.C.dispose();L3.prototype.destroy.call(this)};
g.k.GP=function(){if(this.u){a4(this.context.logger,V3(this).tracking.close);var a=g.cy();a&&this.J&&g.oz(a,this.J);P3(this)}};
g.k.UP=function(){g.N(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.rR=function(){var a=g.cy(),b=V3(this);b=b?b.re:this.re;a&&b&&g.mz(a,[b])};
g.k.qR=function(){var a=g.cy(),b=V3(this);b=b?b.re:this.re;a&&b&&g.nz(a,[b])};
g.k.fO=function(){var a=V3(this);a4(this.context.logger,a.tracking.fM);var b=g.cy();b&&a&&g.mz(b,[a.Li,a.re])};
g.k.tR=function(){var a=g.cy(),b=V3(this);a&&b&&g.nz(a,[b.Li])};
g.k.eO=function(a){var b=V3(this),c=g.cy();this.i?a?(a=this.context.logger,a4(a,b.tracking.Uz),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Li&&g.oz(c,b.Li)):(a=this.context.logger,a4(a,b.tracking.Uz),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.re&&g.oz(c,b.re)):(a=this.context.logger,a4(a,b.tracking.Uz),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.re&&g.oz(c,this.re))};g.w(W3,L3);W3.prototype.ew=function(){L3.prototype.ew.call(this);aNa(this)};
W3.prototype.show=function(){L3.prototype.show.call(this);var a=g.cy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.mz(a,[g.Xx(b.itct)])};
W3.prototype.hide=function(){L3.prototype.hide.call(this);var a=g.cy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.nz(a,[g.Xx(b.itct)])};g.w(X3,W3);
X3.prototype.show=function(){if(!this.isActive){W3.prototype.show.call(this);if(!this.J){g.M(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Fa:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Rl(this.l,!1);var b=this.createElement({D:"div",Fa:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=IMa(this.annotation))&&M3(this,this.l,b,this.annotation.id,
a.session_data);eNa(this,a);this.J=!0}g.Rl(this.element,!0);this.isActive=!0;this.l&&bNa(this,this.l)}};
X3.prototype.hide=function(){this.isActive&&(W3.prototype.hide.call(this),g.Rl(this.element,!1),this.isActive=!1)};
X3.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);W3.prototype.destroy.call(this)};g.w(Y3,W3);g.k=Y3.prototype;g.k.show=function(){this.isActive||(W3.prototype.show.call(this),this.V||(gNa(this),this.V=!0),g.Rl(this.element,!0),g.mh(function(){g.Oq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,$3(this),hNa(this),iNa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.VA=function(a,b,c,d,e,f){return this.isCollapsed?!1:W3.prototype.VA.call(this,a,b,c,d,e,f)};
g.k.DQ=function(a){this.L=!0;Z3(this,500,a)};
g.k.CQ=function(){this.L=!1;jNa(this)};
g.k.xQ=function(a){a.stopPropagation();this.hide()};
g.k.yQ=function(a){a.stopPropagation();$3(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();W3.prototype.destroy.call(this)};g.w(b4,g.rN);g.k=b4.prototype;g.k.Ye=function(a,b){if(!xNa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.N1(b))&&c4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(SMa(this.i,b),g3(this.player)),!0}return null};
g.k.getOptions=function(){return xNa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.hq=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.lH||a.V.get(b.videoId)||g.DH(b)||g.EH(b)?!0:!1};
g.k.Zy=function(){if(this.B){var a=this.player.Za().getVideoContentRect(!0);g.Pl(this.B.element,a.width,a.height);g.Il(this.B.element,a.left,a.top)}if(this.i){var b=this.player.cj();a=this.i;b=b.width;g.N(a.B,"iv-drawer-small",426>=b);g.N(a.B,"iv-drawer-big",1280<=b)}};
g.k.gO=function(a){mNa(this,a.state);g.U(a.state,2)&&(this.ph()&&this.fk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.rs(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Fs(h)&&h.responseXML?h.responseXML:null)&&(c4(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.rN.prototype.load.call(this);mNa(this,this.player.ub());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Au()&&(a=pNa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().V.get(d);f&&qNa(e,f);f=f&&(f.gx||f.Pt);if(!c.il||f)c.Ja?nNa(this,c.Ja,e):(this.u=function(){b.ob(e)},this.player.addEventListener("videodatachange",this.u));
g.hN(this.player,this.B.element,4);this.Zy();(f=g.DH(c))&&vNa(this,f);(f=g.EH(c))&&f.featuredChannel&&wNa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.ob=function(a){var b=this.player.getVideoData();b.Ja&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),nNa(this,b.Ja,a))};
g.k.unload=function(){this.player.Te("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,g3(this.player));this.V=!1;this.G&&(this.G.abort(),this.G=null);this.J={};this.l.hide();g.rN.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.dL=function(a){a===this.player.getVideoData().videoId&&(this.loaded?rNa(this):this.load())};
g.k.ph=function(){return!!this.i&&this.i.isAvailable()};
g.k.fk=function(){this.ph();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ph();this.i&&(a?c?O3(this.i,c,b):O3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):P3(this.i))};
g.k.rs=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.T().V.unsubscribe("vast_info_card_add",this.dL,this);g.Oq(this.player.getRootNode(),g.JT.IV_DRAWER_OPEN);for(var a=this.Z,b=0,c=a.length;b<c;b++)g.Bu(a[b]);this.Z.length=0;g.rN.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.CN.annotations_module=b4;g.CN.creatorendscreen=s3;})(_yt_player);
