(function(g){var window=this;'use strict';var h4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},i4=function(a){return g.XF(a)&&a.X("web_player_i_see_captions_3")},BNa=function(a,b){return g.E(this,function d(){var e,f,h;
return g.B(d,function(l){if(1==l.i)return e=a+"|"+b,g.A(l,g.Sw(),2);if(3!=l.i){f=l.l;if(!f)throw g.ew("gct");return g.A(l,(0,g.GG)(),3)}h=l.l;return l.return(h.get("captions",e))})})},CNa=function(a,b){var c=new g.IG;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},DNa=function(a,b,c){BNa(a,b).then(function(d){d&&c(d.trackData,new g.IG(d.metadata))})},j4=function(){this.segments=[]},ENa=function(a,b){var c=g.wb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.lb(a.segments,c),g.lb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.tb(a.segments,c,0,b),g.tb(a.segments,c+1,0,b)))},k4=function(a,b,c,d,e,f){g.F.call(this);
this.policy=a;this.player=b;this.V=c;this.J=d;this.C=e;this.L=f;this.W=this.player.T();this.B=new j4;this.l=this.u=this.i=null;this.G=new g.K(this.NJ,1E3,this);this.events=new g.kN(this);g.J(this,this.G);g.J(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.aG);this.aG();this.NJ()},FNa=function(a){return a.i&&a.i.C?a.i.C+a.player.Oc()<a.player.getCurrentTime():!1},GNa=function(a,b){var c=g.QC(g.kD(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.dh(g.nt(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.Cka(e);if(h){e=g.kD(a.u,a.policy,{});a.u.ej(e,h);GNa(a,a.u);break a}f||null==a.J||(h=a.u.i[0],a.C?a.J(e.response,1E3*(h.startTime+a.player.Oc())):a.J(e.responseText,1E3*(h.startTime+a.player.Oc())))}a.u=null;a.l=null}}),function(){a.u=null;
a.l=null;a.ma()});
a.u=b;ENa(a.B,a.u.i[0].La)},l4=function(a,b){g.uN.call(this,b.T());
this.i=a;this.I=b;this.u=null;this.C=!1;this.G=g.$F(this.I.T())&&!this.i.isManifestless},INa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.wN(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.LLa.get(e);null==n&&(n=HNa[e]||HNa[e.replace(/-/g,"_")],g.LLa.set(e,n));h=n||h}c.push(new g.IG({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},JNa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},KNa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.wN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},m4=function(a){if(!LNa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(MNa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},n4=function(a,b,c,d,e,f){var h={};
g.Pa(h,b);g.Pa(h,a.params);g.Pa(h,c);var l={};g.Pa(l,b.dd);a.params.dd&&g.Pa(l,a.params.dd);g.Pa(l,c.dd);h.dd=l;g.V.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.Ff?"rtl":"ltr",tabindex:"0",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.xa=!1;this.l=a;this.Aa=this.ya=null;this.playerWidth=e;this.playerHeight=f;this.G=null;this.maxWidth=.96*e;this.Ra=.96*f;this.i=h;this.wb=c;this.Ea=b;this.B=this.Ca("captions-text");
this.jb=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Ja=d/360*16;this.type=0;this.Ta=this.Ja*NNa(l);a=new g.Nx(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.jO,this);a.subscribe("dragmove",this.iO,this);a.subscribe("dragend",this.hO,this);this.eb=this.bb=0;b="";this.i.windowOpacity&&(a=m4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+")");a={"background-color":b,display:!1===
this.i.isVisible?"none":"","text-align":ONa[this.i.textAlign]};this.jb&&(a["border-radius"]=b?this.Ta/8+"px":"");if(this.u=2===this.l.params.Ff||3===this.l.params.Ff)b=this.element,c="vertical-rl",1===this.i.YE&&(c="vertical-lr"),g.he&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Bl(b,"-o-writing-mode",c),g.Bl(b,"-webkit-writing-mode",c),g.Bl(b,"writing-mode",c),g.Bl(b,"text-orientation","upright"),g.M(b,"ytp-vertical-caption"),3===this.l.params.Ff&&(g.Bl(b,"text-orientation",""),g.Bl(b,"transform","rotate(180deg)"));
g.Bl(this.element,a);switch(this.i.Uh){case 0:case 1:case 2:g.M(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M(this.element,"ytp-caption-window-bottom")}},NNa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},PNa=function(a,b){var c={},d=b.background?b.background:a.i.dd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.dd.backgroundOpacity;d=m4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.jb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Ta/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ja*NNa(b)+"px";d=1;e=b.color||a.i.dd.color;if(b.color||null!=b.textOpacity)e=m4(e),d=null==b.textOpacity?a.i.dd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.QB&&(h=e=b.QB);var l=a.Ja/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Et()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.dd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ij&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.YQ&&(c.visibility="hidden");1===b.eJ&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.dG||g.fj,3===a.l.params.Ff?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Cj||2===b.Cj||3===b.Cj||4===b.Cj||5===b.Cj)if(g.dG)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Cj){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},QNa=function(a){a.G=g.qg("SPAN");
g.Bl(a.G,{display:"block"});g.M(a.G,"caption-visual-line");a.B.appendChild(a.G)},RNa=function(a,b){var c=g.qg("SPAN");
g.Bl(c,{display:"inline-block","white-space":"pre-wrap"});g.Bl(c,PNa(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.Bl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Bl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},SNa=function(a,b,c){a.xa=a.xa||!!c;
var d={};g.Pa(d,a.i.dd);g.Pa(d,c||b.i);g.Pa(d,a.wb.dd);(c=!a.G)&&QNa(a);for(var e=a.ya&&a.Aa&&g.Ub(d,a.Aa)?a.ya:RNa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(QNa(a),e=RNa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.rg(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.dG||!g.El(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.El(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.lg?g.Bl(e,m,"1em"):g.Bl(e,m,"0.5em")))}a.Aa=d;a.ya=e;a.C.push(b)},o4=function(a,b,c){g.uN.call(this,a);
this.videoData=b;this.audioTrack=c;this.B=b.qB},p4=function(a,b,c,d,e,f,h){n4.call(this,a,b,c,d,e,f,h);
this.type=1},q4=function(a,b,c,d,e,f,h){n4.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.V=this.L=this.Ia=0;this.Y=NaN;this.fb=0;this.rb=null;this.Ka=new g.K(this.gU,433,this);g.M(this.element,"ytp-caption-window-rollup");g.J(this,this.Ka);g.Bl(this.element,"overflow","hidden")},TNa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.YE&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},UNa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.dm,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Fm)?(e=g.qg("SPAN"),g.xg(e,"\u2013".repeat(d)),g.Bl(e,PNa(a,a.i.dd)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.V=c.call(b,a.Y,a.fb,(a.u?d.offsetHeight:d.offsetWidth)+1)},VNa=function(a,b){UNa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.Ia){var d=0<c&&0===a.Ia;b||isNaN(c)||d||(g.M(a.element,"ytp-rollup-mode"),g.Gq(a.Ka));g.Bl(a.B,"transform",TNa(a,c));a.Ia=c}UNa(a)},r4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.aA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},s4=function(a,b,c,d,e){g.aA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},WNa=function(a){var b="_"+t4++;
return new s4(0,0x8000000000000,0,b,a)},YNa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Ud){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=XNa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new r4(a,b,e,c,l,d,m)}switch(m.Ud){case 9:case 10:m.Cj=1;break;case 11:m.Cj=2;break;case 12:m.Cj=3;break;case 13:m.Cj=4;break;case 14:m.Cj=5}return new r4(a,b,e,c,l.textContent||"",d,m)},XNa=function(a,b,c,d,e){var f=g.Et(),h=
f?g.qg("DIV"):g.qg("RUBY"),l=g.qg("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.qg("DIV"):g.qg("RP");a.textContent=b;h.appendChild(a);b=f?g.qg("DIV"):g.qg("RT");b.textContent=c;h.appendChild(b);c=e.Ud;if(10===c||11===c||12===c||13===c||14===c)if(g.Bl(b,"text-emphasis-style","filled circle"),g.Bl(b,"text-emphasis-color","currentcolor"),g.Bl(b,"webkit-text-emphasis","filled circle"),11===e.Ud||13===e.Ud)g.Bl(b,"webkit-text-emphasis-position","under left"),g.Bl(b,"text-emphasis-position","under left");c=!0;if(4===e.Ud||7===e.Ud||12===e.Ud||
14===e.Ud)g.Bl(h,"ruby-position","over"),g.Bl(h,"-webkit-ruby-position","before");else if(5===e.Ud||6===e.Ud||11===e.Ud||13===e.Ud)g.Bl(h,"ruby-position","under"),g.Bl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.qg("DIV"):g.qg("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Bl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Bl(f,"display","none"),f=f.nextElementSibling,g.Bl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Bl(h.lastElementChild,"display","none"),d?(g.Bl(h,"padding-top","0.6em"),g.Bl(f,"top","0")):(g.Bl(h,"padding-bottom","0.6em"),g.Bl(f,"bottom","0")));return h},u4=function(){g.F.apply(this,arguments)},v4=function(a){u4.call(this);
this.C=a;this.B={};this.V={};this.Z={};this.G="_"+t4++;this.L={};this.u=this.i=null;this.J=!0},w4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},x4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},y4=function(a,b){a=w4(a,b);
return void 0!==a?a:null},A4=function(a,b){a=a.getAttribute(b);
if(null!=a)return z4.test(a),a},ZNa=function(a,b){var c={},d=b.getAttribute("ws");
g.Pa(c,d?a.Z[d]:a.C);a=y4(b,"mh");null!=a&&(c.Tr=a);a=y4(b,"ju");null!=a&&(c.textAlign=a);a=y4(b,"pd");null!=a&&(c.Ff=a);a=y4(b,"sd");null!=a&&(c.YE=a);a=A4(b,"wfc");null!=a&&(c.windowColor=a);b=w4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},$Na=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Pa(c,a.V[d]);a=y4(b,"ap");null!=a&&(c.Uh=a);a=w4(b,"cc");null!=a&&(c.Fm=a);a=w4(b,"ah");null!=a&&(c.Xg=a);a=w4(b,"rc");null!=a&&(c.dm=a);b=w4(b,"av");null!=b&&(c.Dj=b);return c},aOa=function(a,b,c,d){var e={};
g.Pa(e,$Na(a,b));g.Pa(e,ZNa(a,b));d?g.Ub(e,a.C)?(d=a.G,e=a.C):d="_"+t4++:d=b.getAttribute("id")||"_"+t4++;a=w4(b,"t")+c;b=w4(b,"d")||0x8000000000000;if(2===e.Ff||3===e.Ff)c=e.dm,e.dm=e.Fm,e.Fm=c;return new s4(a,b,0,d,e)},B4=function(a){u4.call(this);
this.G=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},C4=function(a){a=g.Of(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},bOa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.dm=a);b=b.ccColCount;void 0!==b&&(f.Fm=b);if(2===f.Ff||3===f.Ff)b=f.dm,f.dm=f.Fm,f.Fm=b;return new s4(c,d,0,e,f)},E4=function(){this.u=this.time=this.mode=this.l=0;
this.B=new D4(this);this.C=new D4(this);this.i=[];this.clear()},dOa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Qo:a,
Am:b,result:0};a=cOa[a];b=cOa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Am===d;if(d)return{Qo:a,Am:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Qo:a,Am:b,result:2};return{Qo:a,Am:b,result:3}},fOa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,eOa(a.B,b,c,d))},gOa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?fOa(a,d.LH,d.MH,b):1===d.type&&a.l&496&&eOa(a.C,d.LH,d.MH,b);a.i.length=0},F4=function(){this.type=0},G4=function(){this.state=this.Am=this.Qo=0},hOa=function(){this.timestamp=this.i=0},H4=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new F4;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new hOa}},I4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},mOa=function(a,b){switch(a){case 0:return iOa[(b&127)-32];
case 1:return jOa[b&15];case 2:return kOa[b&31];case 3:return lOa[b&31]}return 0},J4=function(a){return a.u[a.row][a.l]},K4=function(a,b,c){2<=b&&1<a.l&&(--a.l,J4(a).i=0);
var d=J4(a);d.timestamp=a.C.time+0;d.i=mOa(b,c);32>a.l&&a.l++},nOa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},L4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},M4=function(a){a.row=0<a.i?a.i:1;
a.l=1;L4(a,0,15)},N4=function(a){this.u=a;
this.C=0;this.style=new F4;this.G=new H4(this.u);this.J=new H4(this.u);this.text=new H4(this.u);this.l=this.G;this.B=this.J;this.i=this.l},O4=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(I4(d,c),M4(a.l),M4(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(I4(d,c),L4(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},oOa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},pOa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},D4=function(a){this.i=a;
this.C=0;this.u=new N4(this.i);this.G=new N4(this.i);this.l=new G4;this.B=this.u},eOa=function(a,b,c,d){a.l.update();
b=dOa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Qo;c=b.Am;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&K4(a,0,b),c&96&&K4(a,0,c),0!==b&&0!==c&&3===a.style.type&&I4(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.Qo=e,b.Am=c,b.state=2,b=e&8?a.G:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;nOa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));L4(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:K4(b.i,0,32);break a;case 48:57===c?(d=b.i,J4(d).i=0,32>d.l&&d.l++):K4(b.i,1,c&15)}break;case 2:c&32&&K4(b.i,2,c&31);break;case 3:c&32&&K4(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:oOa(b);
break;case 33:d=b.i;1<d.l&&(--d.l,J4(d).i=0);break;case 36:d=b.i;b=J4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:O4(b,2,d);break;case 38:O4(b,3,d);break;case 39:O4(b,4,d);break;case 40:K4(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);M4(d);pOa(b);break;case 43:pOa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:I4(a,d)}L4(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;I4(a,d);nOa(a,b,b+1,a.i-1);L4(a,a.row,1)}break;case 46:L4(b.B,0,15);break;case 47:I4(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,oOa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},qOa=function(){},P4=function(a,b,c){this.trackData=a;
this.G=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.trackData);this.l=[]},Q4=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},R4=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},S4=function(a,b){u4.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new E4;this.i.l=1<<this.track},T4=function(a){if("string"===typeof a)return!1;
a=new P4(a,8,0);return rOa(a)},rOa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==R4(a))return!1;
a.version=Q4(a);if(1<a.version)return!1;Q4(a);Q4(a);Q4(a);return!0},U4=function(){u4.call(this)},sOa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.ij=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new r4(b,c,d,e.id,p.nodeValue,f||0<n,g.Rb(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Pa(r,l);sOa(a,b,c,d,e,!0,p,r,m)}}},V4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},tOa=function(a,b,c,d){d=Object.assign({Tr:0},d);
return new s4(a,b,c,"_"+t4++,d)},W4=function(a){g.F.call(this);
this.W=a;this.i=null},zOa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.W.X("enable_h5_ssdai_caption")&&b){var f=e,h=uOa(b,d),l=[];try{for(var m=g.q(h),n=m.next();!n.done;n=m.next()){var p=n.value,r=p.trackData,t=p.QE;l="string"!==typeof r?l.concat(vOa(a,c,r,t,f)):"WEBVTT"===r.substring(0,6)?l.concat(wOa(a,r,t)):l.concat(xOa(a,c,r,t))}var u=l}catch(x){g.ny(x),a.clear(),u=[]}if(0!==u.length)return u}a.W.X("html5_disable_rawcc_killswitch")?"string"!==typeof b&&(u=new DataView(b),8<=u.byteLength&&1718909296===u.getUint32(4)&&(u=g.nC(u,0,1835295092),b=a.W.X("html5_fix_mdat_offset_killswitch")?
b.slice(u.dataOffset,u.dataOffset+u.size):b.slice(u.dataOffset,u.offset+u.size),T4(b)||(b=g.Ya(new Uint8Array(b))))):b=yOa(a,b);if(!b)return[];try{return"string"!==typeof b?vOa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?wOa(a,b,d):xOa(a,c,b,d)}catch(x){return g.ny(x),a.clear(),[]}},yOa=function(a,b){if("string"===typeof b||T4(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.nC(c,0,1835295092);if(!c||!c.size)return"";a=a.W.X("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.Ya(new Uint8Array(a))},uOa=function(a,b){if("string"===typeof a||T4(a))return[{trackData:a,
QE:b}];var c=new DataView(a);if(8>=c.byteLength||1718909296!==c.getUint32(4))return[];var d=g.yC(c,1835295092);if(!d||!d.length||!d[0].size)return[];var e=[];d=g.q(d.entries());for(var f=d.next();!f.done;f=d.next()){var h=g.q(f.value);f=h.next().value;h=h.next().value;h=g.Ya(new Uint8Array(a.slice(h.dataOffset,h.offset+h.size)));e.push({trackData:h,QE:b+1E3*f})}AOa(c,e,b);return e=e.filter(function(l){return!!l.trackData})},AOa=function(a,b,c){var d=g.nC(a,0,1836476516),e=9E4;
d&&(e=g.pC(d)||9E4);d=0;var f=g.yC(a,1836019558);f=g.q(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.q(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.nC(a,l.dataOffset,1953653094))&&(l=g.nC(a,l.dataOffset,1952867444))&&(l=g.vC(l)/e*1E3,0===h&&(d=l),b[h].QE=l-d+c||c*h*1E3)}},vOa=function(a,b,c,d,e){if(!T4(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new S4(e,b));return a.i.l(c,d)},wOa=function(a,b,c){a.i||(a.i=new U4);
a=a.i.l(b,c);.01>Math.random()&&g.oy(Error("Deprecated subtitles format in web player: WebVTT"));return a},xOa=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new B4(BOa(b))),a.i.l(c,d)}catch(f){return g.ny(f),[]}var e=g.N1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new v4(BOa(b),a.W)),a.i.l(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},BOa=function(a){var b=
{};
if(a=g.LG(a))b.lang=a,COa.test(a)&&(b.Ff=1);return b},Z4=function(a){g.rN.call(this,a);
var b=this;this.I=a;this.W=this.I.T();this.videoData=this.I.getVideoData();this.eb=this.I.Za();this.B={dd:{}};this.C={dd:{}};this.xa=[];this.L={};this.Ja={};this.Z=!1;this.rb=g.LH(this.videoData);this.Ya=g.Eta(this.videoData,this.I);this.jb=!!this.videoData.captionTracks.length;this.wb=!!this.videoData.Tb;this.Ia="3"===this.W.controlsType;this.l=this.G=this.J=this.Ea=this.Ta=null;this.Ka=new W4(this.W);this.i=null;this.Y=new g.kN(this);this.Ra=new g.V({D:"div",K:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
var c=null,d=g.ur("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.er(d));this.storage=c;c=a.bd();this.bb=!(null===c||void 0===c||!c.uw());this.u=DOa(this);this.V=!this.u&&this.Ia&&this.bb&&this.Ya;g.J(this,this.Ka);this.u?this.Aa=this.ya=null:(this.ya=new g.Cq(this.pF,void 0,this),g.J(this,this.ya),this.Aa=new g.K(this.rV,2E3,this),g.J(this,this.Aa));g.J(this,this.Y);this.W.X("caption_window_container_killswitch")||g.hN(this.player,this.Ra.element,4);g.J(this,this.Ra);this.u||this.Y.N(a,
"resize",this.rF);(this.fb=!g.Cx()&&!this.I.isFullscreen()&&!this.u&&!this.V&&!this.W.X("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.Y.N(a,"resize",this.kT);this.Y.N(a,"onPlaybackAudioChange",this.nS);this.Y.N(a,g.dA("captions"),function(e){b.Ad(e)});
this.Y.N(a,g.eA("captions"),function(e){b.lf(e)});
X4(this,Y4(this,"display-settings")||{})},FOa=function(a){if(1===a.W.Ra||1===a.videoData.vt||"alwayson"===g.vH(a.videoData,"yt:cc"))return!0;
if(2===a.W.Ra){var b;g.bG(a.W)?b=EOa(a):b=Y4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().l;b=h4(a.player.getAudioTrack(),i4(a.W));var d=g.vH(a.videoData,"yt:cc");if(void 0===$4(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.vH(a.videoData,"yt:cc")},a5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.l},$4=function(a){var b=void 0,c=g.tv(g.qv.getInstance(),65);
if(g.bG(a.W)&&null!=c){if(null!=EOa(a))return!1;b=!c}return b},GOa=function(a){var b;
a.rb?b=new o4(a.W,a.videoData,a.player.getAudioTrack(),a.player):a.Ya?b=new l4(a.videoData.i,a.player):a.jb?b=new g.vN(a.W,a.videoData,a.player.getAudioTrack()):b=new g.xN(a.W,a.videoData.Tb,a.videoData.videoId,g.$na(a.videoData),a.videoData.Lj);return b},c5=function(a,b){if(a.l){if(a.G&&a.G.B)return a.G.B;
b||(b=a.wb?!1:a.jb?!1:!0);b=g.sN(a.l.l,b);for(var c=[a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.vH(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.LG(b[e])===c[d])return b[e];return a.G&&a.G.u?a.G.u:(c=b.find(function(f){return f.isDefault}))?c:b[0]||b5(a)}return null},b5=function(a){return a.G&&a.G.i},d5=function(a){var b=b5(a);
return!!b&&a.i===b},HOa=function(a){var b=h4(a.player.getAudioTrack(),i4(a.W)),c;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===b?$4(a)||a.Z||FOa(a)?c=c5(a,a.Z):a5(a)&&(c=b5(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=c5(a,a.Z):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&a5(a)&&(c=b5(a));if(a.u||a.V){var d=g.sN(a.l.l,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.qg("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.JG(f));h.setAttribute("srclang",g.LG(f));h.setAttribute("id",f.toString());a.V||h.setAttribute("src",a.l.xp(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.I.bd();c.Gt(b);c=c.Fe();a.bb&&a.Y.N(c.textTracks,"change",a.NU)}else!a.i&&c&&e5(a,c),a.player.Ma("onCaptionsTrackListChanged"),a.player.Ma("onApiChange")},IOa=function(a,b){var c=a.I.bd().Fe().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},e5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Z=c,a.Z&&(g.bG(a.W)?f5(a,!!b):g5(a,"module-enabled",!!b)));a.i=b;a5(a)&&(a.i=b5(a));a.load()},JOa=function(a,b){a.W.X("caption_window_container_killswitch")?g.hN(a.player,b,4):a.Ra.element.appendChild(b)},KOa=function(a,b){var c=a.eb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.LG(a.i):null;d&&COa.test(d)&&(b.params.Ff=1);d=a.eb.getPlayerSize();switch(null!=b.params.Tr?b.params.Tr:1<b.i.length?1:0){case 1:return new p4(b,a.B,a.C,c,d.width,d.height,a.W.experiments);case 2:return new q4(b,a.B,a.C,c,d.width,d.height,a.W.experiments);default:return new n4(b,a.B,a.C,c,d.width,d.height,a.W.experiments)}},X4=function(a,b,c){c=void 0===c?!1:c;
var d=h5.dd;a.B={};g.Pa(a.B,h5);a.B.dd={};g.Pa(a.B.dd,d);a.C={dd:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;z4.test(f);e.dd.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;z4.test(f);e.dd.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||h5.windowColor;z4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.dd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.dd.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.ij?3:d.bold?1:d.ij?2:0);f=f.dd;switch(e){case 1:f.bold=!0;delete f.ij;break;case 2:delete f.bold;f.ij=!0;break;case 3:f.bold=!0;f.ij=!0;break;default:delete f.bold,delete f.ij}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.dd.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=h5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.dd.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.dd.fontFamily=f;a.loaded&&a.rF();c&&g5(a,"display-settings",b)},MOa=function(a,b){b&&!a.J?(b=WNa({Ff:0,
lang:"en"}),a.J=[b,new r4(b.start,b.end-b.start,0,b.id,"Captions look like this")],a.player.Gd(a.J)):!b&&a.J&&(LOa(a,a.J),a.J=null)},LOa=function(a,b){a.player.Pf(b);
g.Bb(b,function(c){g.nb(this.xa,c)},a);
g.Dq(a.ya)},Y4=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},g5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},f5=function(a,b){a.I.isInline()||(0,g.tLa)(b)},EOa=function(a){if(!a.I.isInline())return(0,g.Xsa)()},DOa=function(a){var b=a.I.bd();
b=!(null===b||void 0===b||!b.qw());return a.Ia&&b&&!a.Ya};
g.zS.prototype.xu=g.ca(31,function(a){var b=2;this.xa.has(a)?b=0:g.Iya(this,a)&&(b=1);return b});
g.CV.prototype.xu=g.ca(30,function(a){return this.Dd.xu(a)});
g.LN.prototype.Zq=g.ca(29,function(){this.ma();for(var a=g.cg(document,"track",void 0,this.i),b=0;b<a.length;b++)g.ug(a[b])});
g.mS.prototype.Zq=g.ca(28,function(){this.oa.Zq()});
g.LN.prototype.uw=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.mS.prototype.uw=g.ca(26,function(){return this.oa.uw()});
g.LN.prototype.qw=g.ca(25,function(){return!!this.i.textTracks});
g.mS.prototype.qw=g.ca(24,function(){return this.oa.qw()});
g.LN.prototype.Gt=g.ca(23,function(a){this.ma();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.mS.prototype.Gt=g.ca(22,function(a){this.oa.Gt(a)});
g.uN.prototype.hE=g.ca(21,function(){return!1});
g.uN.prototype.zn=g.ca(20,function(){});
g.vN.prototype.zn=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.xp(a,b);this.jm();this.i=g.it(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.xN.prototype.zn=g.ca(18,function(a,b,c){var d=this;this.isDisposed();b=this.xp(a,b);this.jm();this.i=g.it(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.lV.prototype.Ku=g.ca(6,function(){return this.J});
g.RX.prototype.Ku=g.ca(5,function(){var a;return(null===(a=g.jN(this))||void 0===a?void 0:a.Fu())||null});
g.aN.prototype.Fu=g.ca(4,function(){return this.app.Ku()});
g.vX.prototype.Fu=g.ca(3,function(){var a;return(null===(a=this.Ua)||void 0===a?void 0:a.Ku())||null});
var COa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,HNa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",
as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",
bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",
cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",
en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",
fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",
hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",
kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",
ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",
mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",
mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",
nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",
rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",
sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",
su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",
tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",
xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
j4.prototype.contains=function(a){a=g.wb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
j4.prototype.length=function(){return this.segments.length/2};
g.w(k4,g.F);g.k=k4.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.l&&this.l.cancel()};
g.k.aG=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Oc();var b=this.i;this.i=g.cb(this.V.Xm(a).i);b!==this.i&&this.L&&this.L()};
g.k.reset=function(){this.B=new j4;this.l&&(this.l.cancel(),this.l=null)};
g.k.NJ=function(){var a;this.isDisposed();var b;if(b=null!=this.i)b=this.i,b=b.i.pm(b);if(b&&!this.l&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.Us(b);if(this.W.X("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.Fu();if(c){var d=b.i[0].La,e=c.yr(b.i[0].B,d,b.i[0].i.info.id,3);if(e)if(c=c.xu(d),0===c)e&&(b.u=new g.KB(e));else if(2===c){this.G.start();FNa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}b.i[0].duration?(this.B.contains(b.i[0].La)||GNa(this,b),this.i=g.cb(b.i)):!g.S(this.W.experiments,"force_caption_seek_for_live_killswitch")&&FNa(this)&&this.seekTo(this.player.getCurrentTime())}this.G.start()};
g.k.ma=function(){};
g.w(l4,g.uN);g.k=l4.prototype;g.k.zn=function(a,b,c){var d=this;this.jm();b=JNa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?KNa(this,b,"386"):KNa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.Cta(this.W);this.u=new k4(f,this.I,b,function(h,l){c(h,a,l,e)},this.G||g.ED(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.k.hE=function(){var a=this.C;this.C=!1;return a};
g.k.Pr=function(a){var b=this.G?[new g.IG({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.IG({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?INa(this,"386"):INa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.tN(this.l,c.value);a()};
g.k.jm=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.xp=function(){return""};
var z4=/^#(?:[0-9a-f]{3}){1,2}$/i,MNa=/#(.)(.)(.)/,LNa=/^#(?:[0-9a-f]{3}){1,2}$/i;var ONa=["left","right","center","justify"];g.w(n4,g.V);g.k=n4.prototype;g.k.jO=function(a,b){var c=g.Ol(this.element,this.element.parentElement);this.bb=a-c.x;this.eb=b-c.y;g.M(this.element,"ytp-dragging")};
g.k.iO=function(a,b){var c=g.Ql(this.element);a=a-this.bb-.02*this.playerWidth;var d=b-this.eb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Of(e,0,2));var f=(d+c.height/2)/this.Ra*3;f=Math.floor(g.Of(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Of(a,0,1);c=(d+f/2*c.height)/this.Ra;c=100*g.Of(c,0,1);this.l.params.Uh=b;this.l.params.Dj=c;this.l.params.Xg=a;this.i.Uh=b;this.i.Dj=c;this.i.Xg=a;this.Ea.Uh=b;this.Ea.Dj=c;this.Ea.Xg=a;this.HL()};
g.k.hO=function(){g.Oq(this.element,"ytp-dragging")};
g.k.HL=function(){this.ys(this.C)};
g.k.Ob=function(){return this.type};
g.k.ys=function(a){var b=Math.min(this.HI(),this.maxWidth),c=this.GI(),d="";3===this.l.params.Ff&&(d="rotate(180deg)");g.Bl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.AB(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Xg+2;d=this.i.Uh;switch(d){case 0:case 3:case 6:(b=this.i.dd.fontSizeIncrement)&&0<b&&2!==this.i.Ff&&3!==
this.i.Ff&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Dj+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Bl(this.element,
a)};
g.k.AB=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.xa||this.C.length>b)b=0,this.xa=!1,this.C=[],this.G=this.Aa=this.ya=null,g.sg(this.B);for(;b<a.length;b++)SNa(this,a[b])};
g.k.HI=function(){return 0};
g.k.GI=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.w(o4,g.uN);o4.prototype.zn=function(a,b,c){DNa(this.videoData.videoId,a.vssId,c)};
o4.prototype.Pr=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.tN(this.l,c.value);a()};g.w(p4,n4);p4.prototype.AB=function(a){var b=this.l.i;n4.prototype.AB.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Pa(d,c.i);g.Pa(d,NOa);var e=c.i;var f=d}SNa(this,c,d)}};
var NOa={YQ:!0};g.w(q4,n4);g.k=q4.prototype;g.k.HL=function(){g.Hq(this.Ka)};
g.k.gU=function(){g.Oq(this.element,"ytp-rollup-mode");this.ys(this.rb,!0)};
g.k.GI=function(){return this.u?this.V:this.L};
g.k.HI=function(){return this.u?this.L:this.V};
g.k.ys=function(a,b){this.rb=a;if(this.l.params.dm){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.fb=this.V;this.L=this.V=0;n4.prototype.ys.call(this,a);VNa(this,b)}n4.prototype.ys.call(this,a)};g.w(r4,g.aA);r4.prototype.toString=function(){return g.aA.prototype.toString.call(this)};g.w(s4,g.aA);s4.prototype.toString=function(){return g.aA.prototype.toString.call(this)};
var t4=0;g.w(u4,g.F);u4.prototype.l=function(){return[]};
u4.prototype.reset=function(){};g.w(v4,u4);v4.prototype.reset=function(){this.L={};this.u=this.i=null;this.J=!0};
v4.prototype.l=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.B,h={},l=a.getAttribute("p");l&&g.Pa(h,this.B[l]);l=x4(a,"b");null!=l&&(h.bold=
l);l=x4(a,"i");null!=l&&(h.ij=l);l=x4(a,"u");null!=l&&(h.underline=l);l=y4(a,"et");null!=l&&(h.charEdgeStyle=l);l=y4(a,"of");null!=l&&(h.offset=l);l=A4(a,"bc");null!=l&&(h.background=l);l=A4(a,"ec");null!=l&&(h.QB=l);l=A4(a,"fc");null!=l&&(h.color=l);l=y4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=w4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=w4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=w4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=y4(a,"rb");null!=l&&10!==l&&0!==l&&(h.Ud=10<l?l-
1:l);a=y4(a,"hg");null!=a&&(h.eJ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=ZNa(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=$Na(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=aOa(this,a,b,!1);(a=this.L[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.L[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.G;h=!!x4(a,"a");l=(w4(a,
"t")||0)+l;var m=w4(a,"d")||5E3;h||(!this.J&&this.u&&this.u.windowId===f&&this.u.end>l&&(this.u.end=l),this.u&&"\n"===this.u.text&&(this.u.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.B[p]:null;var r=Array.from(a.childNodes);r.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var u=r[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.B[u]:null)&&u.Ud&&(1===u.Ud?(u=r.slice(t,t+4),4===u.length&&(x=YNa(l,m,
f,h,n,u,this.B),t+=3)):x=YNa(l,m,f,h,n,[y],this.B)),!x){var z=y;x=l;y=m;u=f;var G=h,H=n,I=z.textContent?z.textContent:"",L=z.getAttribute("p");L=L?this.B[L]:null;z=w4(z,"t")||0;x=new r4(x+z,y-z,H,u,I,G,L)}}else x=new r4(l,m,n,f,u.textContent||"",h,p);c.push(x);this.u=x}if(0<c.length)for(c[0].windowId===this.G&&(this.i=aOa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var OOa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(B4,u4);B4.prototype.reset=function(){this.u.clear()};
B4.prototype.l=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.ij=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.QB=C4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=C4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=C4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Ud=10<h?h-1:h,f.Cj=OOa.get(f.Ud));e.hgHorizGroup&&(f.eJ=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.C.get(h)):Object.assign(f,
this.G),void 0!==e.mhModeHint&&(f.Tr=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Ff=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.YE=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=C4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.C.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.B.get(h)),void 0!==e.ahHorPos&&
(f.Xg=e.ahHorPos),void 0!==e.apPoint&&(f.Uh=e.apPoint),void 0!==e.avVerPos&&(f.Dj=e.avVerPos),void 0!==e.ccCols&&(f.Fm=e.ccCols),void 0!==e.rcRows&&(f.dm=e.rcRows),this.B.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=bOa(this,l,d,e,f),a.push(d),this.u.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+t4++,h=bOa(this,l,d,e,f),a.push(h),this.u.set(f,h));0===e&&(e=5E3);h=this.u.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.Tr?h.params.Tr:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Ud)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.i.get(z))&&z.Ud&&2===z.Ud?(z=p[t+2].pPenId,z=this.i.get(z),!z||!z.Ud||3>z.Ud?t=!1:(z=p[t+3].pPenId,t=(z=this.i.get(z))&&
z.Ud&&2===z.Ud?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var G=this.i.get(p[l+2].pPenId);u=XNa(u,x,z,t,G);m=new r4(d,e,n,f,u,m,y);l+=3}else m=new r4(d+x,e-x,n,h.id,u,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};E4.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
E4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var cOa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];F4.prototype.set=function(a){this.type=a};
F4.prototype.get=function(){return this.type};
G4.prototype.clear=function(){this.state=0};
G4.prototype.update=function(){this.state=2===this.state?1:0};
G4.prototype.isValid=function(){return 0!==this.state};
G4.prototype.matches=function(a,b){return this.isValid()&&a===this.Qo&&b===this.Am};
hOa.prototype.reset=function(){this.timestamp=this.i=0};
H4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
H4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
H4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var iOa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],jOa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],kOa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],lOa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];N4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.G;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.G.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
D4.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.G.reset(a,1)};qOa.prototype.B=function(){};g.w(P4,qOa);P4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+t4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new s4(c,d-c,5,f,{textAlign:0,Uh:0,Xg:2.5*b,Dj:5.33*a});e=new r4(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.w(S4,u4);S4.prototype.l=function(a){a=new P4(a,a.byteLength,this.u);if(rOa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=R4(a)*(1E3/45):1===a.version&&(a.u=4294967296*R4(a)+R4(a)),a.C=Q4(a);0<a.C;a.C--){var b=Q4(a),c=Q4(a),d=Q4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,LH:c,MH:d,order:b.i.length}))}gOa(this.i,a);return a.l}return[]};
S4.prototype.reset=function(){this.i.clear()};g.w(U4,u4);
U4.prototype.l=function(a,b){var c=[];a=a.split(POa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!QOa.test(e)){var h=i5.exec(e);if(h&&4<=h.length){var l=V4(h[1]),m=V4(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var r="";var t=null,u="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Dj=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.Xg=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||r||(r="end");if(!t)switch(h.textAlign){case 0:h.Xg=0;break;case 1:h.Xg=100;break;case 2:h.Xg=50}if(null!=h.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;h.Uh=r}e=e.substring(i5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=tOa(l,m,5,u),m=new r4(l,m,5,f.id,h,!1,g.Rb(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(ROa),1===r.length?(h=5,u=tOa(l,m,h,u)):(p=h=6,u=Object.assign({Fm:32},u),u=new s4(l,m,p,"_"+t4++,u)),c.push(u),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.N1("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,sOa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=V4(n)+f}i5.lastIndex=0}}return c};
var QOa=/^NOTE/,POa=/(?:\r\n|\r|\n){2,}/,i5=/^((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})[\t ]+--\x3e[\t ]+((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})(?:[\t ]*)(.*)(?:\r\n|\r|\n)/gm,ROa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.pS.jy(U4,{l:"wvppt"});g.w(W4,g.F);W4.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
W4.prototype.reset=function(){this.i&&this.i.reset()};
W4.prototype.va=function(){g.F.prototype.va.call(this);this.clear()};var h5={windowColor:"#080808",windowOpacity:0,textAlign:2,Uh:7,Xg:50,Dj:100,dd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(Z4,g.rN);g.k=Z4.prototype;g.k.va=function(){if(this.u||this.V){var a=this.I.bd();a&&!a.isDisposed()&&a.Zq()}else MOa(this,!1);g.rN.prototype.va.call(this)};
g.k.hq=function(){if(this.Ia)return this.u||this.V;var a=h4(this.player.getAudioTrack(),i4(this.W));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?a5(this):$4(this)||a5(this)?!0:FOa(this)};
g.k.load=function(){var a=this;g.rN.prototype.load.call(this);var b=!g.S(this.W.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();this.l?(this.i&&(this.Ka.clear(),this.u?IOa(this,!0):3!==this.player.getPresentingPlayerType()&&this.l.zn(this.i,"json3",function(c,d,e,f){c&&(a.l.hE()&&(a.xa=[],a.I.Te("captions"),g.Dq(a.ya),a.Ka.reset()),c=zOa(a.Ka,c,d,e,f),a.player.Gd(c),!a.Z||a.V||d5(a)||g.NF(a.W)||g.FF(a.W)||(g.Iq(a.Aa),c=WNa({Uh:0,Xg:5,Dj:5,dm:2,textAlign:0,
Ff:0,lang:"en"}),a.Ea=[c],d=["Click "," for settings"],a.Ta||(e=new g.hL(g.xL()),g.J(a,e),a.Ta=e.element),e=c.end-c.start,(f=g.JG(a.i))&&a.Ea.push(new r4(c.start,e,0,c.id,f)),a.Ea.push(new r4(c.start,e,0,c.id,d[0]),new r4(c.start,e,0,c.id,a.Ta,!0),new r4(c.start,e,0,c.id,d[1],!0)),a.player.Gd(a.Ea),g.Gq(a.Aa)),!a.Z||a.V||d5(a)||(g.bG(a.W)?f5(a,!0):g5(a,"module-enabled",!0),a.G&&(a.G.B=a.i),a.player.rq()),a.Z=!1)}),!b||this.u||this.V||d5(this)||this.player.Ma("captionschanged",g.KG(this.i))),b||(this.i&&
!d5(this)?this.player.Ma("captionschanged",g.KG(this.i)):this.player.Ma("onCaptionsTrackListChanged"))):(this.l=GOa(this),g.J(this,this.l),this.l.Pr(function(){HOa(a)}))};
g.k.unload=function(){this.u&&this.i?IOa(this,!1):(this.Aa&&g.Iq(this.Aa),this.player.Te("captions"),this.xa=[],this.l&&this.l.jm(),this.Ka.clear(),this.J&&this.player.Gd(this.J),this.rF());g.rN.prototype.unload.call(this);this.player.rq();this.player.Ma("captionschanged",{})};
g.k.create=function(){this.hq()&&this.load()};
g.k.NU=function(){for(var a=this.I.bd().Fe().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.sN(this.l.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&e5(this,b,!0)};
g.k.iW=function(){!this.i&&this.u||this.unload()};
g.k.Ad=function(a){this.xa.push(a);g.Dq(this.ya)};
g.k.lf=function(a){g.nb(this.xa,a);this.l instanceof l4&&this.l.G&&this.player.Pf([a]);g.Dq(this.ya)};
g.k.lV=function(a){if(a instanceof s4){var b=this.L[a.id];b&&b.l!==a&&(b.dispose(),delete this.L[a.id],b=null);b||(b=KOa(this,a))&&(this.L[a.id]=b)}else b=a.windowId,this.Ja[b]||(this.Ja[b]=[]),this.Ja[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Ra.element.id};
g.k.rV=function(){LOa(this,this.Ea);this.Ea=null};
g.k.pF=function(){var a=this;if(!this.fb||!this.u){this.ya.stop();g.Sb(this.Ja);this.xa.sort(g.cA);var b=this.xa;if(this.J){var c=g.So(b,function(d){return-1===this.J.indexOf(d)},this);
c.length&&(b=c)}g.Bb(b,this.lV,this);g.Db(this.L,function(d,e){a.Ja[e]?(d.element.parentNode||(d instanceof q4||d instanceof p4||g.Gb(a.L,function(f,h){h!==e&&f.l.params.Uh===d.l.params.Uh&&f.l.params.Xg===d.l.params.Xg&&f.l.params.Dj===d.l.params.Dj&&(f.dispose(),delete a.L[h]);return h===e},a),JOa(a,d.element)),d.ys(a.Ja[e])):(d.dispose(),delete a.L[e])},this)}};
g.k.uV=function(){X4(this,{},!0);g.S(this.W.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Ma("captionssettingschanged")};
g.k.tQ=function(){var a=h5.dd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.ij?3:a.bold?1:a.ij?2:0,textOpacity:a.textOpacity,windowColor:h5.windowColor,windowOpacity:h5.windowOpacity};var b=Y4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.EM=function(a,b){var c={};g.Pa(c,Y4(this,"display-settings"));g.Pa(c,a);X4(this,c,b);this.player.Ma("captionssettingschanged")};
g.k.rF=function(){!this.u&&this.loaded&&(g.Db(this.L,function(a,b){a.dispose();delete this.L[b]},this),this.pF())};
g.k.Ye=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Of(b,-2,4);this.EM({fontSizeIncrement:c});return c;case "reload":b&&!this.u&&e5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.W.u&&(g.bG(this.W)?f5(this,!!b):g5(this,"module-enabled",!!b));break;case "track":if(!this.l)return{};if(b){if(this.u)break;if(!g.La(b))break;if(g.Rb(b)){e5(this,null,!0);break}a=g.sN(this.l.l,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?CNa(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=(0,g.Wsa)(),a=g.LG(c),b.length&&a===b[b.length-1]||(b.push(a),(0,g.uLa)(b)),e5(this,c,!0))}else return this.loaded&&this.i&&!d5(this)?g.KG(this.i):{};return"";case "tracklist":return this.l?g.Re(g.sN(this.l.l,!(!b||!b.includeAsr)),function(f){return g.KG(f)}):[];
case "translationLanguages":return this.l?this.l.B.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.u||void 0===b||MOa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.u&&a.push("stickyLoading");return a};
g.k.KC=function(){var a=this.i;return a?{cc:a.vssId}:{}};
g.k.WV=function(){this.loaded&&this.i&&!d5(this)?(g.bG(this.W)?f5(this,!1):g5(this,"module-enabled",!1),this.unload(),a5(this,!0)&&e5(this,b5(this),!1)):this.mM()};
g.k.mM=function(){this.loaded&&this.i||e5(this,d5(this)||!this.i?c5(this,!0):this.i,!0)};
g.k.nS=function(){var a=d5(this);a5(this,a)?e5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.hq()&&(a?e5(this,c5(this),!1):this.load()))};
g.k.kT=function(){if(this.I.isFullscreen())this.u=this.Ia=!0,this.loaded&&HOa(this);else{var a=this.I.bd();a&&!a.isDisposed()&&a.Zq();this.Ia="3"===this.W.controlsType;this.u=DOa(this)}e5(this,this.i)};
g.pS.jy(Z4,{pF:"smucd"});g.CN.captions=Z4;})(_yt_player);
